FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm ci --legacy-peer-deps

COPY src ./src
COPY tsconfig.json ./

ENV NODE_ENV=production

CMD ["npx", "tsx", "src/worker/index.ts"]
